Repository sebs-scholarship/Blog, pull requests merged in 2020-05, with the labels that each got.

#6 Added Volunteers post and cover image support
  .github/workflows/test.yml
  _config.yml
  _drafts/Keeping-Costs-Low.md
  _layouts/default.html
  _layouts/post.html
  _posts/2020-04-26-Welcome.md
  _posts/2020-05-01-Meet-the-Vounteers-1.md
  assets/css/style.css
  assets/images/Chris.jpg
  assets/images/Dakota.jpg
  assets/images/Holly.jpg
  assets/images/Lucie.jpg
  assets/images/savings-cover.jpg
  assets/images/volunteers-cover.jpg
  examples/posts/2020-04-20-Test-Post.md
  index.html
Labels: Post, enhancement

#7 Added code for OpenGraph to enhance sharing
  _layouts/default.html
Labels: enhancement

#8 Added more OpenGraph social code to site
  _layouts/default.html
Labels: enhancement

#9 Added code for better automation
  Gemfile
  _config.yml
  _layouts/default.html
  robots.txt
  sitemap.xml
Labels: enhancement

#10 Moved post to publishable source
  _posts/2020-05-04-Keeping-Costs-Low.md
Labels: Post

#11 Added volunteers pt2 post
  _posts/2020-05-08-Meet-the-Vounteers-2.md
  assets/images/Alaska.jpg
  assets/images/Antonio.jpg
  assets/images/Kaylee.jpg
  assets/images/Levi.jpg
  assets/images/Trey.jpg
Labels: Post

#12 Added blog email address to footer of post layout
  .github/workflows/test.yml
  _layouts/post.html
Labels: enhancement

#13 Added 2020 recipient announcement post
  _posts/2020-05-15-Recipient-Announcement.md
  assets/images/2020-recipient-announcement.jpg
  assets/images/Cassandra.jpg
  assets/images/Marianna.jpg
Labels: Post

#14 Feature/footer
  _layouts/default.html
Labels: enhancement

#15 Updated "by" line in footer
  _layouts/default.html
Labels: enhancement

#16 Added college tips post
  _posts/2020-05-22-College-Tips.md
  assets/images/5-college-tips.jpg
Labels: post, under review

#17 Added Facebook like button and comment section
  _includes/facebook_share.html
  _includes/linkedin_share.html
  _layouts/post.html
Labels: enhancement

#18 Added Facebook comments section and Pinterest save button
  _includes/facebook_share.html
  _includes/linkedin_share.html
  _layouts/post.html
  _posts/2020-05-28-Social-Update.md
  assets/css/style.css
  assets/images/social-update.jpg
  assets/images/social.jpg
Labels: enhancement, post
